/**
 * The MIT License (MIT)
 *
 * Copyright (c) 2019 Erik Moqvist
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

/**
 * This file was generated by pbtools.
 */

#include <limits.h>
#include "msg.h"

#if CHAR_BIT != 8
#    error "Number of bits in a char must be 8."
#endif

void uiohook_key_data_init(
    struct uiohook_key_data_t *self_p,
    struct pbtools_heap_t *heap_p)
{
    self_p->base.heap_p = heap_p;
    self_p->key_code = 0;
    self_p->raw_code = 0;
    self_p->key_char = 0;
}

void uiohook_key_data_encode_inner(
    struct pbtools_encoder_t *encoder_p,
    struct uiohook_key_data_t *self_p)
{
    pbtools_encoder_write_uint32(encoder_p, 4, self_p->key_char);
    pbtools_encoder_write_uint32(encoder_p, 3, self_p->raw_code);
    pbtools_encoder_write_uint32(encoder_p, 2, self_p->key_code);
}

void uiohook_key_data_decode_inner(
    struct pbtools_decoder_t *decoder_p,
    struct uiohook_key_data_t *self_p)
{
    int wire_type;

    while (pbtools_decoder_available(decoder_p)) {
        switch (pbtools_decoder_read_tag(decoder_p, &wire_type)) {

        case 2:
            self_p->key_code = pbtools_decoder_read_uint32(decoder_p, wire_type);
            break;

        case 3:
            self_p->raw_code = pbtools_decoder_read_uint32(decoder_p, wire_type);
            break;

        case 4:
            self_p->key_char = pbtools_decoder_read_uint32(decoder_p, wire_type);
            break;

        default:
            pbtools_decoder_skip_field(decoder_p, wire_type);
            break;
        }
    }
}

void uiohook_key_data_encode_repeated_inner(
    struct pbtools_encoder_t *encoder_p,
    int field_number,
    struct uiohook_key_data_repeated_t *repeated_p)
{
    pbtools_encode_repeated_inner(
        encoder_p,
        field_number,
        (struct pbtools_repeated_message_t *)repeated_p,
        sizeof(struct uiohook_key_data_t),
        (pbtools_message_encode_inner_t)uiohook_key_data_encode_inner);
}

void uiohook_key_data_decode_repeated_inner(
    struct pbtools_decoder_t *decoder_p,
    struct pbtools_repeated_info_t *repeated_info_p,
    struct uiohook_key_data_repeated_t *repeated_p)
{
    pbtools_decode_repeated_inner(
        decoder_p,
        repeated_info_p,
        (struct pbtools_repeated_message_t *)repeated_p,
        sizeof(struct uiohook_key_data_t),
        (pbtools_message_init_t)uiohook_key_data_init,
        (pbtools_message_decode_inner_t)uiohook_key_data_decode_inner);
}

struct uiohook_key_data_t *
uiohook_key_data_new(
    void *workspace_p,
    size_t size)
{
    return (pbtools_message_new(
                workspace_p,
                size,
                sizeof(struct uiohook_key_data_t),
                (pbtools_message_init_t)uiohook_key_data_init));
}

int uiohook_key_data_encode(
    struct uiohook_key_data_t *self_p,
    uint8_t *encoded_p,
    size_t size)
{
    return (pbtools_message_encode(
                &self_p->base,
                encoded_p,
                size,
                (pbtools_message_encode_inner_t)uiohook_key_data_encode_inner));
}

int uiohook_key_data_decode(
    struct uiohook_key_data_t *self_p,
    const uint8_t *encoded_p,
    size_t size)
{
    return (pbtools_message_decode(
                &self_p->base,
                encoded_p,
                size,
                (pbtools_message_decode_inner_t)uiohook_key_data_decode_inner));
}

void uiohook_mouse_data_init(
    struct uiohook_mouse_data_t *self_p,
    struct pbtools_heap_t *heap_p)
{
    self_p->base.heap_p = heap_p;
    self_p->button = 0;
    self_p->clicks = 0;
    self_p->x = 0;
    self_p->y = 0;
}

void uiohook_mouse_data_encode_inner(
    struct pbtools_encoder_t *encoder_p,
    struct uiohook_mouse_data_t *self_p)
{
    pbtools_encoder_write_int32(encoder_p, 5, self_p->y);
    pbtools_encoder_write_int32(encoder_p, 4, self_p->x);
    pbtools_encoder_write_uint32(encoder_p, 3, self_p->clicks);
    pbtools_encoder_write_uint32(encoder_p, 2, self_p->button);
}

void uiohook_mouse_data_decode_inner(
    struct pbtools_decoder_t *decoder_p,
    struct uiohook_mouse_data_t *self_p)
{
    int wire_type;

    while (pbtools_decoder_available(decoder_p)) {
        switch (pbtools_decoder_read_tag(decoder_p, &wire_type)) {

        case 2:
            self_p->button = pbtools_decoder_read_uint32(decoder_p, wire_type);
            break;

        case 3:
            self_p->clicks = pbtools_decoder_read_uint32(decoder_p, wire_type);
            break;

        case 4:
            self_p->x = pbtools_decoder_read_int32(decoder_p, wire_type);
            break;

        case 5:
            self_p->y = pbtools_decoder_read_int32(decoder_p, wire_type);
            break;

        default:
            pbtools_decoder_skip_field(decoder_p, wire_type);
            break;
        }
    }
}

void uiohook_mouse_data_encode_repeated_inner(
    struct pbtools_encoder_t *encoder_p,
    int field_number,
    struct uiohook_mouse_data_repeated_t *repeated_p)
{
    pbtools_encode_repeated_inner(
        encoder_p,
        field_number,
        (struct pbtools_repeated_message_t *)repeated_p,
        sizeof(struct uiohook_mouse_data_t),
        (pbtools_message_encode_inner_t)uiohook_mouse_data_encode_inner);
}

void uiohook_mouse_data_decode_repeated_inner(
    struct pbtools_decoder_t *decoder_p,
    struct pbtools_repeated_info_t *repeated_info_p,
    struct uiohook_mouse_data_repeated_t *repeated_p)
{
    pbtools_decode_repeated_inner(
        decoder_p,
        repeated_info_p,
        (struct pbtools_repeated_message_t *)repeated_p,
        sizeof(struct uiohook_mouse_data_t),
        (pbtools_message_init_t)uiohook_mouse_data_init,
        (pbtools_message_decode_inner_t)uiohook_mouse_data_decode_inner);
}

struct uiohook_mouse_data_t *
uiohook_mouse_data_new(
    void *workspace_p,
    size_t size)
{
    return (pbtools_message_new(
                workspace_p,
                size,
                sizeof(struct uiohook_mouse_data_t),
                (pbtools_message_init_t)uiohook_mouse_data_init));
}

int uiohook_mouse_data_encode(
    struct uiohook_mouse_data_t *self_p,
    uint8_t *encoded_p,
    size_t size)
{
    return (pbtools_message_encode(
                &self_p->base,
                encoded_p,
                size,
                (pbtools_message_encode_inner_t)uiohook_mouse_data_encode_inner));
}

int uiohook_mouse_data_decode(
    struct uiohook_mouse_data_t *self_p,
    const uint8_t *encoded_p,
    size_t size)
{
    return (pbtools_message_decode(
                &self_p->base,
                encoded_p,
                size,
                (pbtools_message_decode_inner_t)uiohook_mouse_data_decode_inner));
}

void uiohook_wheel_data_init(
    struct uiohook_wheel_data_t *self_p,
    struct pbtools_heap_t *heap_p)
{
    self_p->base.heap_p = heap_p;
    self_p->type = 0;
    self_p->clicks = 0;
    self_p->x = 0;
    self_p->y = 0;
    self_p->amount = 0;
    self_p->rotation = 0;
    self_p->direction = 0;
}

void uiohook_wheel_data_encode_inner(
    struct pbtools_encoder_t *encoder_p,
    struct uiohook_wheel_data_t *self_p)
{
    pbtools_encoder_write_uint32(encoder_p, 7, self_p->direction);
    pbtools_encoder_write_int32(encoder_p, 6, self_p->rotation);
    pbtools_encoder_write_uint32(encoder_p, 5, self_p->amount);
    pbtools_encoder_write_int32(encoder_p, 4, self_p->y);
    pbtools_encoder_write_int32(encoder_p, 3, self_p->x);
    pbtools_encoder_write_uint32(encoder_p, 2, self_p->clicks);
    pbtools_encoder_write_uint32(encoder_p, 1, self_p->type);
}

void uiohook_wheel_data_decode_inner(
    struct pbtools_decoder_t *decoder_p,
    struct uiohook_wheel_data_t *self_p)
{
    int wire_type;

    while (pbtools_decoder_available(decoder_p)) {
        switch (pbtools_decoder_read_tag(decoder_p, &wire_type)) {

        case 1:
            self_p->type = pbtools_decoder_read_uint32(decoder_p, wire_type);
            break;

        case 2:
            self_p->clicks = pbtools_decoder_read_uint32(decoder_p, wire_type);
            break;

        case 3:
            self_p->x = pbtools_decoder_read_int32(decoder_p, wire_type);
            break;

        case 4:
            self_p->y = pbtools_decoder_read_int32(decoder_p, wire_type);
            break;

        case 5:
            self_p->amount = pbtools_decoder_read_uint32(decoder_p, wire_type);
            break;

        case 6:
            self_p->rotation = pbtools_decoder_read_int32(decoder_p, wire_type);
            break;

        case 7:
            self_p->direction = pbtools_decoder_read_uint32(decoder_p, wire_type);
            break;

        default:
            pbtools_decoder_skip_field(decoder_p, wire_type);
            break;
        }
    }
}

void uiohook_wheel_data_encode_repeated_inner(
    struct pbtools_encoder_t *encoder_p,
    int field_number,
    struct uiohook_wheel_data_repeated_t *repeated_p)
{
    pbtools_encode_repeated_inner(
        encoder_p,
        field_number,
        (struct pbtools_repeated_message_t *)repeated_p,
        sizeof(struct uiohook_wheel_data_t),
        (pbtools_message_encode_inner_t)uiohook_wheel_data_encode_inner);
}

void uiohook_wheel_data_decode_repeated_inner(
    struct pbtools_decoder_t *decoder_p,
    struct pbtools_repeated_info_t *repeated_info_p,
    struct uiohook_wheel_data_repeated_t *repeated_p)
{
    pbtools_decode_repeated_inner(
        decoder_p,
        repeated_info_p,
        (struct pbtools_repeated_message_t *)repeated_p,
        sizeof(struct uiohook_wheel_data_t),
        (pbtools_message_init_t)uiohook_wheel_data_init,
        (pbtools_message_decode_inner_t)uiohook_wheel_data_decode_inner);
}

struct uiohook_wheel_data_t *
uiohook_wheel_data_new(
    void *workspace_p,
    size_t size)
{
    return (pbtools_message_new(
                workspace_p,
                size,
                sizeof(struct uiohook_wheel_data_t),
                (pbtools_message_init_t)uiohook_wheel_data_init));
}

int uiohook_wheel_data_encode(
    struct uiohook_wheel_data_t *self_p,
    uint8_t *encoded_p,
    size_t size)
{
    return (pbtools_message_encode(
                &self_p->base,
                encoded_p,
                size,
                (pbtools_message_encode_inner_t)uiohook_wheel_data_encode_inner));
}

int uiohook_wheel_data_decode(
    struct uiohook_wheel_data_t *self_p,
    const uint8_t *encoded_p,
    size_t size)
{
    return (pbtools_message_decode(
                &self_p->base,
                encoded_p,
                size,
                (pbtools_message_decode_inner_t)uiohook_wheel_data_decode_inner));
}

int uiohook_msg_key_alloc(
    struct uiohook_msg_t *self_p)
{
    self_p->data = uiohook_msg_data_key_e;

    return (pbtools_sub_message_alloc(
                (struct pbtools_message_base_t **)&self_p->key_p,
                self_p->base.heap_p,
                sizeof(struct uiohook_key_data_t),
                (pbtools_message_init_t)uiohook_key_data_init));
}

int uiohook_msg_mouse_alloc(
    struct uiohook_msg_t *self_p)
{
    self_p->data = uiohook_msg_data_mouse_e;

    return (pbtools_sub_message_alloc(
                (struct pbtools_message_base_t **)&self_p->mouse_p,
                self_p->base.heap_p,
                sizeof(struct uiohook_mouse_data_t),
                (pbtools_message_init_t)uiohook_mouse_data_init));
}

int uiohook_msg_wheel_alloc(
    struct uiohook_msg_t *self_p)
{
    self_p->data = uiohook_msg_data_wheel_e;

    return (pbtools_sub_message_alloc(
                (struct pbtools_message_base_t **)&self_p->wheel_p,
                self_p->base.heap_p,
                sizeof(struct uiohook_wheel_data_t),
                (pbtools_message_init_t)uiohook_wheel_data_init));
}

static void uiohook_msg_key_decode(
    struct pbtools_decoder_t *decoder_p,
    int wire_type,
    struct uiohook_msg_t *self_p)
{
    self_p->data = uiohook_msg_data_key_e;
    pbtools_decoder_sub_message_decode(
        decoder_p,
        wire_type,
        (struct pbtools_message_base_t **)&self_p->key_p,
        sizeof(struct uiohook_key_data_t),
        (pbtools_message_init_t)uiohook_key_data_init,
        (pbtools_message_decode_inner_t)uiohook_key_data_decode_inner);
}

static void uiohook_msg_mouse_decode(
    struct pbtools_decoder_t *decoder_p,
    int wire_type,
    struct uiohook_msg_t *self_p)
{
    self_p->data = uiohook_msg_data_mouse_e;
    pbtools_decoder_sub_message_decode(
        decoder_p,
        wire_type,
        (struct pbtools_message_base_t **)&self_p->mouse_p,
        sizeof(struct uiohook_mouse_data_t),
        (pbtools_message_init_t)uiohook_mouse_data_init,
        (pbtools_message_decode_inner_t)uiohook_mouse_data_decode_inner);
}

static void uiohook_msg_wheel_decode(
    struct pbtools_decoder_t *decoder_p,
    int wire_type,
    struct uiohook_msg_t *self_p)
{
    self_p->data = uiohook_msg_data_wheel_e;
    pbtools_decoder_sub_message_decode(
        decoder_p,
        wire_type,
        (struct pbtools_message_base_t **)&self_p->wheel_p,
        sizeof(struct uiohook_wheel_data_t),
        (pbtools_message_init_t)uiohook_wheel_data_init,
        (pbtools_message_decode_inner_t)uiohook_wheel_data_decode_inner);
}

void uiohook_msg_init(
    struct uiohook_msg_t *self_p,
    struct pbtools_heap_t *heap_p)
{
    self_p->base.heap_p = heap_p;
    self_p->type = 0;
    self_p->time = 0;
    self_p->mask = 0;
    self_p->reserved = 0;
    self_p->data = 0;
}

void uiohook_msg_encode_inner(
    struct pbtools_encoder_t *encoder_p,
    struct uiohook_msg_t *self_p)
{
    pbtools_encoder_write_uint32(encoder_p, 4, self_p->reserved);
    pbtools_encoder_write_uint32(encoder_p, 3, self_p->mask);
    pbtools_encoder_write_uint64(encoder_p, 2, self_p->time);
    pbtools_encoder_write_uint32(encoder_p, 1, self_p->type);
    switch (self_p->data) {

    case uiohook_msg_data_key_e:
        pbtools_encoder_sub_message_encode_always(
            encoder_p,
            5,
            &self_p->key_p->base,
            (pbtools_message_encode_inner_t)uiohook_key_data_encode_inner);
        break;

    case uiohook_msg_data_mouse_e:
        pbtools_encoder_sub_message_encode_always(
            encoder_p,
            6,
            &self_p->mouse_p->base,
            (pbtools_message_encode_inner_t)uiohook_mouse_data_encode_inner);
        break;

    case uiohook_msg_data_wheel_e:
        pbtools_encoder_sub_message_encode_always(
            encoder_p,
            7,
            &self_p->wheel_p->base,
            (pbtools_message_encode_inner_t)uiohook_wheel_data_encode_inner);
        break;

    default:
        break;
    }
}

void uiohook_msg_decode_inner(
    struct pbtools_decoder_t *decoder_p,
    struct uiohook_msg_t *self_p)
{
    int wire_type;

    while (pbtools_decoder_available(decoder_p)) {
        switch (pbtools_decoder_read_tag(decoder_p, &wire_type)) {

        case 1:
            self_p->type = pbtools_decoder_read_uint32(decoder_p, wire_type);
            break;

        case 2:
            self_p->time = pbtools_decoder_read_uint64(decoder_p, wire_type);
            break;

        case 3:
            self_p->mask = pbtools_decoder_read_uint32(decoder_p, wire_type);
            break;

        case 4:
            self_p->reserved = pbtools_decoder_read_uint32(decoder_p, wire_type);
            break;

        case 5:
            uiohook_msg_key_decode(
                decoder_p,
                wire_type,
                self_p);
            break;

        case 6:
            uiohook_msg_mouse_decode(
                decoder_p,
                wire_type,
                self_p);
            break;

        case 7:
            uiohook_msg_wheel_decode(
                decoder_p,
                wire_type,
                self_p);
            break;

        default:
            pbtools_decoder_skip_field(decoder_p, wire_type);
            break;
        }
    }
}

void uiohook_msg_encode_repeated_inner(
    struct pbtools_encoder_t *encoder_p,
    int field_number,
    struct uiohook_msg_repeated_t *repeated_p)
{
    pbtools_encode_repeated_inner(
        encoder_p,
        field_number,
        (struct pbtools_repeated_message_t *)repeated_p,
        sizeof(struct uiohook_msg_t),
        (pbtools_message_encode_inner_t)uiohook_msg_encode_inner);
}

void uiohook_msg_decode_repeated_inner(
    struct pbtools_decoder_t *decoder_p,
    struct pbtools_repeated_info_t *repeated_info_p,
    struct uiohook_msg_repeated_t *repeated_p)
{
    pbtools_decode_repeated_inner(
        decoder_p,
        repeated_info_p,
        (struct pbtools_repeated_message_t *)repeated_p,
        sizeof(struct uiohook_msg_t),
        (pbtools_message_init_t)uiohook_msg_init,
        (pbtools_message_decode_inner_t)uiohook_msg_decode_inner);
}

struct uiohook_msg_t *
uiohook_msg_new(
    void *workspace_p,
    size_t size)
{
    return (pbtools_message_new(
                workspace_p,
                size,
                sizeof(struct uiohook_msg_t),
                (pbtools_message_init_t)uiohook_msg_init));
}

int uiohook_msg_encode(
    struct uiohook_msg_t *self_p,
    uint8_t *encoded_p,
    size_t size)
{
    return (pbtools_message_encode(
                &self_p->base,
                encoded_p,
                size,
                (pbtools_message_encode_inner_t)uiohook_msg_encode_inner));
}

int uiohook_msg_decode(
    struct uiohook_msg_t *self_p,
    const uint8_t *encoded_p,
    size_t size)
{
    return (pbtools_message_decode(
                &self_p->base,
                encoded_p,
                size,
                (pbtools_message_decode_inner_t)uiohook_msg_decode_inner));
}
